# Generated by Django 5.1.4 on 2025-03-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='Reasons',
        ),
        migrations.AddField(
            model_name='records',
            name='reasons',
            field=models.TextField(null=True),
        ),
    ]
