# Generated by Django 5.1.4 on 2025-03-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_records_reasons_records_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='alternative_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
