# Generated by Django 5.1.4 on 2025-03-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_records_alternative_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='reasons',
            field=models.TextField(blank=True, null=True),
        ),
    ]
