# Generated by Django 5.1.4 on 2025-03-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_records_reasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='reasons',
        ),
    ]
