# Generated by Django 5.1.4 on 2025-03-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_records_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
