# Generated by Django 5.1.4 on 2025-03-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_records_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
