# Generated by Django 5.1.4 on 2025-03-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_records_reasons_alter_records_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='reasons',
        ),
    ]
