# Generated by Django 5.1.4 on 2025-03-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_records_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
